"""Bounded correlation context for Comet operations.

Only identifiers generated by Comet are admitted here.  The mutable request
flags intentionally survive context copies made by Starlette/AnyIO while a new
instance is installed for every detached task.
"""

from __future__ import annotations

import asyncio
import contextvars
import secrets
import threading
from collections.abc import Coroutine, Iterator
from contextlib import contextmanager
from enum import IntFlag
from typing import TypeVar

_T = TypeVar("_T")


class TerminalFlag(IntFlag):
    BUSINESS_SEEN = 1
    BUSINESS_FAILURE_EXPLAINED = 2
    TRANSPORT_FAILURE_EXPLAINED = 4


class RequestTerminalFlags:
    """Thread-safe terminal state shared by copies of one request context."""

    __slots__ = ("_flags", "_lock", "_terminal_owners")

    def __init__(self) -> None:
        self._flags = TerminalFlag(0)
        self._lock = threading.Lock()
        self._terminal_owners: set[str] = set()

    def mark(self, flags: TerminalFlag) -> None:
        with self._lock:
            self._flags |= flags

    def snapshot(self) -> TerminalFlag:
        with self._lock:
            return self._flags

    def admit_terminal(self, event: str, flags: TerminalFlag) -> bool:
        """Atomically admit one terminal per owner event for this request."""

        with self._lock:
            if event in self._terminal_owners:
                return False
            self._terminal_owners.add(event)
            self._flags |= flags
            return True


request_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "comet_request_id", default=None
)
run_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "comet_run_id", default=None
)
connection_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "comet_connection_id", default=None
)
request_terminal_flags_var: contextvars.ContextVar[RequestTerminalFlags | None] = (
    contextvars.ContextVar("comet_request_terminal_flags", default=None)
)


def new_correlation_id() -> str:
    return secrets.token_hex(16)


def current_request_id() -> str | None:
    return request_id_var.get()


def current_run_id() -> str | None:
    return run_id_var.get()


def current_connection_id() -> str | None:
    return connection_id_var.get()


def current_terminal_flags() -> RequestTerminalFlags | None:
    return request_terminal_flags_var.get()


@contextmanager
def request_context(request_id: str | None = None) -> Iterator[str]:
    identifier = request_id or new_correlation_id()
    request_token = request_id_var.set(identifier)
    flags_token = request_terminal_flags_var.set(RequestTerminalFlags())
    try:
        yield identifier
    finally:
        request_terminal_flags_var.reset(flags_token)
        request_id_var.reset(request_token)


@contextmanager
def run_context(run_id: str | None = None) -> Iterator[str]:
    identifier = run_id or new_correlation_id()
    token = run_id_var.set(identifier)
    try:
        yield identifier
    finally:
        run_id_var.reset(token)


@contextmanager
def connection_context(connection_id: str | None = None) -> Iterator[str]:
    identifier = connection_id or new_correlation_id()
    token = connection_id_var.set(identifier)
    try:
        yield identifier
    finally:
        connection_id_var.reset(token)


def clear_context() -> None:
    """Clear inherited process context, notably in executor initializers."""

    request_id_var.set(None)
    run_id_var.set(None)
    connection_id_var.set(None)
    request_terminal_flags_var.set(RequestTerminalFlags())


def _observe_detached(task: asyncio.Task[object], *, task_name: str) -> None:
    if task.cancelled():
        return
    try:
        exc = task.exception()
    except (asyncio.CancelledError, asyncio.InvalidStateError):
        return
    if exc is None:
        return
    try:
        # Import lazily to keep this module independent from the logging backend.
        from comet.observability.logging import log

        log.error(
            "task.failed",
            "Detached task failed",
            task_name=task_name,
            error_code="unexpected_failure",
            exc=exc,
        )
    except Exception:
        pass


def create_detached_task[T](
    coroutine: Coroutine[object, object, _T],
    *,
    name: str,
    run_id: str | None = None,
    keep_connection: bool = False,
) -> asyncio.Task[_T]:
    """Create an observed task without accidentally retaining request state."""

    detached = contextvars.copy_context()
    detached.run(request_id_var.set, None)
    if not keep_connection:
        detached.run(connection_id_var.set, None)
    detached.run(run_id_var.set, run_id or new_correlation_id())
    detached.run(request_terminal_flags_var.set, RequestTerminalFlags())
    task = asyncio.create_task(coroutine, name=name, context=detached)
    task.add_done_callback(
        lambda completed: _observe_detached(completed, task_name=name),
        context=detached,
    )
    return task


__all__ = (
    "RequestTerminalFlags",
    "TerminalFlag",
    "clear_context",
    "connection_context",
    "create_detached_task",
    "current_connection_id",
    "current_request_id",
    "current_run_id",
    "current_terminal_flags",
    "new_correlation_id",
    "request_context",
    "run_context",
)
