"""Closed, credential-free statistics contract shared with the native engine."""

ENGINE_STAT_BOOLEAN_FIELDS = frozenset(
    {"disk_cache_stats_available", "draining", "spool_stats_available"}
)
ENGINE_STAT_INTEGER_FIELDS = frozenset(
    {
        "requests_active",
        "request_workers",
        "request_body_reserved_bytes",
        "request_body_limit_bytes",
        "request_body_busy_rejections_total",
        "request_queue_busy_rejections_total",
        "sessions",
        "session_prefetches_active",
        "nntp_hedges_active",
        "nntp_hedges_started_total",
        "nntp_hedges_won_total",
        "nntp_salvage_holes_total",
        "nntp_salvage_bytes_total",
        "raw_composites",
        "provider_sets",
        "segment_cache_entries",
        "segment_cache_bytes",
        "disk_cache_mappings",
        "disk_cache_blobs",
        "disk_cache_bytes",
        "spool_resident_bytes",
        "spool_reserved_bytes",
        "archive_jobs_active",
        "repair_jobs_active",
        "archive_busy_rejections_total",
        "repair_busy_rejections_total",
        "spool_rejections_total",
        "negative_cache_entries",
        "network_singleflight_active",
        "nntp_pools",
        "nntp_connections_open",
        "nntp_connections_active",
        "nntp_connections_idle",
        "nntp_queue_interactive",
        "nntp_queue_preparation",
        "nntp_queue_background",
        "nntp_preparation_slots",
        "nntp_reserved_commands",
        "nntp_reserved_encoded_bytes",
        "nntp_reserved_decoded_bytes",
        "nntp_scheduler_busy_rejections_total",
        "nntp_connections_poisoned",
        "nntp_provider_attempts_total",
        "nntp_provider_suppliers_total",
        "nntp_provider_hits_total",
        "nntp_provider_missing_total",
        "nntp_provider_corrupt_total",
        "nntp_provider_failures_total",
        "nntp_provider_cancellations_total",
        "nntp_provider_failovers_total",
    }
)
ENGINE_STAT_FIELDS = ENGINE_STAT_BOOLEAN_FIELDS | ENGINE_STAT_INTEGER_FIELDS
