"""Shared bounds for NZB metadata and native Usenet media."""

MIB = 1024 * 1024
GIB = 1024 * MIB

MAX_NZB_DOCUMENT_BYTES = 150 * MIB
MAX_NZB_METADATA_BYTES = MAX_NZB_DOCUMENT_BYTES
MAX_NZB_FILES = 20_000
MAX_NZB_SEGMENTS = 2_000_000
MAX_ARCHIVE_VOLUMES = MAX_NZB_FILES
MAX_PAR2_VOLUMES = MAX_NZB_FILES
MAX_USENET_LOGICAL_BYTES = 1024 * GIB
MAX_UNIX_SOCKET_PATH_BYTES = 107
