#!/usr/bin/env python3
"""Generate the checked-in API v1 TypeScript contract from FastAPI OpenAPI."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend/src/api/generated/contracts.ts"
_IDENTIFIER = re.compile(r"[^A-Za-z0-9_$]")
sys.path.insert(0, str(ROOT))


def _type_name(reference: str) -> str:
    return reference.rsplit("/", 1)[-1]


def _typescript(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _IDENTIFIER.sub("_", _type_name(schema["$ref"]))
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(
            json.dumps(value, ensure_ascii=False) for value in schema["enum"]
        )
    if "anyOf" in schema:
        return " | ".join(_typescript(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_typescript(item) for item in schema["oneOf"])
    if "allOf" in schema:
        return " & ".join(_typescript(item) for item in schema["allOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_typescript({**schema, "type": item}) for item in schema_type)
    if schema_type == "null":
        return "null"
    if schema_type == "boolean":
        return "boolean"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "array":
        return f"ReadonlyArray<{_typescript(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", ()))
        fields = []
        for key, value in properties.items():
            optional = "" if key in required else "?"
            fields.append(
                f"readonly {json.dumps(key)}{optional}: {_typescript(value)};"
            )
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            fields.append(f"readonly [key: string]: {_typescript(additional)};")
        elif additional is True:
            fields.append("readonly [key: string]: unknown;")
        return "{ " + " ".join(fields) + " }"
    return "unknown"


def _collect_references(value: Any, names: set[str]) -> None:
    if isinstance(value, dict):
        reference = value.get("$ref")
        if isinstance(reference, str):
            names.add(_type_name(reference))
        for nested in value.values():
            _collect_references(nested, names)
    elif isinstance(value, list):
        for nested in value:
            _collect_references(nested, names)


def _operation_type(operation: dict[str, Any], status: str) -> str:
    response = operation.get("responses", {}).get(status, {})
    schema = response.get("content", {}).get("application/json", {}).get("schema", {})
    return _typescript(schema)


def _request_type(operation: dict[str, Any]) -> str:
    schema = (
        operation.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema", {})
    )
    return _typescript(schema) if schema else "never"


def _parameters_type(operation: dict[str, Any]) -> str:
    groups: dict[str, list[str]] = {}
    for parameter in operation.get("parameters", ()):
        location = parameter.get("in")
        name = parameter.get("name")
        if location not in {"header", "path", "query"} or not isinstance(name, str):
            continue
        optional = "" if parameter.get("required") else "?"
        groups.setdefault(location, []).append(
            f"readonly {json.dumps(name)}{optional}: "
            f"{_typescript(parameter.get('schema', {}))};"
        )
    if not groups:
        return "never"
    fields = [
        f"readonly {location}: {{ {' '.join(values)} }};"
        for location, values in sorted(groups.items())
    ]
    return "{ " + " ".join(fields) + " }"


def generate() -> str:
    from comet.api.app import fastapi_app
    from comet.core.config_codec import CONFIGURATION_DICTIONARY_V1

    document = fastapi_app.openapi()
    paths = {
        path: definition
        for path, definition in document["paths"].items()
        if path.startswith("/api/v1/")
    }
    schemas = document.get("components", {}).get("schemas", {})
    referenced: set[str] = set()
    _collect_references(paths, referenced)
    pending = list(referenced)
    while pending:
        name = pending.pop()
        before = set(referenced)
        _collect_references(schemas.get(name, {}), referenced)
        pending.extend(sorted(referenced - before))

    lines = [
        "/* This file is generated by scripts/generate_frontend_contracts.py. */",
        "/* Do not edit it directly. */",
        "",
        "export const CONFIGURATION_DICTIONARY_V1 = "
        + json.dumps(CONFIGURATION_DICTIONARY_V1.decode("ascii"))
        + ";",
        "",
    ]
    for name in sorted(referenced):
        safe_name = _IDENTIFIER.sub("_", name)
        lines.append(f"export type {safe_name} = {_typescript(schemas.get(name, {}))};")
    lines.extend(("", "export interface ApiV1Paths {"))
    for path, definition in sorted(paths.items()):
        lines.append(f"  readonly {json.dumps(path)}: {{")
        for method, operation in sorted(definition.items()):
            if method not in {
                "delete",
                "get",
                "patch",
                "post",
                "put",
            }:
                continue
            lines.extend(
                (
                    f"    readonly {method}: {{",
                    f"      readonly request: {_request_type(operation)};",
                    f"      readonly parameters: {_parameters_type(operation)};",
                    f"      readonly success: {_operation_type(operation, '200')};",
                    f"      readonly error: {_operation_type(operation, '422')};",
                    "    };",
                )
            )
        lines.append("  };")
    lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in contract differs",
    )
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("frontend API contracts are stale")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
